using System;
using System.Collections.Generic;
using System.Linq;
using Godot;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Enchantments;
using MegaCrit.Sts2.Core.Models;

// The public types in this file (EnchantmentStackBehavior / EnchantmentStatusAggregation /
// EnchantmentHookKind / HookExecutionMode / EnchantmentStackDefinition / EnchantmentExecutionPolicy
// / EnchantmentStackSlice / EnchantmentStackSnapshot / MultiEnchantmentStackApi) live in the
// legacy MultiEnchantmentMod namespace rather than MultiEnchantmentMod.Api for historical
// reasons. They surface in v2 public delegate signatures (TrackKeyword, FormatExtraText,
// VisualSlices, ModifyDynamicVar) and ExecutionPolicyBuilder, so downstream mods using v2 must
// `using MultiEnchantmentMod;` alongside `using MultiEnchantmentMod.Api;`.
//
// Moving them into MultiEnchantmentMod.Api would be a source-breaking change for downstream
// authors and is therefore deferred to the next major API version.

namespace MultiEnchantmentMod;

public enum EnchantmentStackBehavior
{
    DisallowDuplicate,
    MergeAmount,
    DuplicateInstance,
    ExistenceStack,
}

public enum EnchantmentStatusAggregation
{
    None,
    Shared,
    PerInstance,
    PresenceOnly,
}

public enum EnchantmentHookKind
{
    OnEnchant,
    OnPlay,
    AfterCardPlayed,
    AfterCardDrawn,
    AfterPlayerTurnStart,
    BeforePlayPhaseStart,
    BeforeFlush,
}

public enum HookExecutionMode
{
    Default,
    MergedTotal,
    PerVisualSlice,
    PerLiveInstance,
    FirstActiveInstanceOnly,
}

public sealed record EnchantmentStackDefinition(
    EnchantmentStackBehavior Behavior,
    EnchantmentStatusAggregation StatusAggregation);

public sealed record EnchantmentExecutionPolicy(
    HookExecutionMode DefaultMode = HookExecutionMode.Default,
    HookExecutionMode OnEnchant = HookExecutionMode.Default,
    HookExecutionMode OnPlay = HookExecutionMode.Default,
    HookExecutionMode AfterCardPlayed = HookExecutionMode.Default,
    HookExecutionMode AfterCardDrawn = HookExecutionMode.Default,
    HookExecutionMode AfterPlayerTurnStart = HookExecutionMode.Default,
    HookExecutionMode BeforePlayPhaseStart = HookExecutionMode.Default,
    HookExecutionMode BeforeFlush = HookExecutionMode.Default)
{
    public HookExecutionMode GetExecutionMode(EnchantmentHookKind hookKind)
    {
        HookExecutionMode mode = hookKind switch
        {
            EnchantmentHookKind.OnEnchant => OnEnchant,
            EnchantmentHookKind.OnPlay => OnPlay,
            EnchantmentHookKind.AfterCardPlayed => AfterCardPlayed,
            EnchantmentHookKind.AfterCardDrawn => AfterCardDrawn,
            EnchantmentHookKind.AfterPlayerTurnStart => AfterPlayerTurnStart,
            EnchantmentHookKind.BeforePlayPhaseStart => BeforePlayPhaseStart,
            EnchantmentHookKind.BeforeFlush => BeforeFlush,
            _ => HookExecutionMode.Default,
        };

        return mode == HookExecutionMode.Default
            ? DefaultMode
            : mode;
    }
}

public sealed record EnchantmentStackSlice(
    int Amount,
    EnchantmentStatus Status,
    int VisualOrder)
{
    public bool IsActive => Status != EnchantmentStatus.Disabled;
}

/// <summary>
/// Author-facing description of one UI badge generated by <c>VisualSlicesWithStatus</c> /
/// <c>GetVisualSlices</c>. <see cref="Amount"/> controls the badge's effective stack amount;
/// <see cref="Status"/> controls whether that badge renders active or disabled. By default, the
/// badge uses the owning enchantment's icon; override with <see cref="WithIcon{TEnchantment}"/>,
/// <see cref="WithIcon(Type)"/>, or <see cref="WithIcon(Texture2D)"/>.
/// </summary>
public sealed record EnchantmentVisualSlice(
    int Amount,
    EnchantmentStatus Status)
{
    public Type? IconEnchantmentType { get; init; }
    public Texture2D? IconTexture { get; init; }

    public static EnchantmentVisualSlice Active(int amount) =>
        new(amount, EnchantmentStatus.Normal);

    public static EnchantmentVisualSlice Disabled(int amount) =>
        new(amount, EnchantmentStatus.Disabled);

    public EnchantmentVisualSlice WithIcon<TEnchantment>()
        where TEnchantment : EnchantmentModel =>
        this with { IconEnchantmentType = typeof(TEnchantment) };

    public EnchantmentVisualSlice WithIcon(Type enchantmentType)
    {
        ArgumentNullException.ThrowIfNull(enchantmentType);
        if (!typeof(EnchantmentModel).IsAssignableFrom(enchantmentType))
        {
            throw new ArgumentException(
                $"{enchantmentType.FullName} is not an {nameof(EnchantmentModel)} subclass.",
                nameof(enchantmentType));
        }

        return this with { IconEnchantmentType = enchantmentType };
    }

    public EnchantmentVisualSlice WithIcon(Texture2D texture)
    {
        ArgumentNullException.ThrowIfNull(texture);
        return this with { IconTexture = texture };
    }
}

public sealed record EnchantmentStackSnapshot(
    CardModel? Card,
    Type EnchantmentType,
    EnchantmentModel AnchorInstance,
    EnchantmentStackDefinition Definition,
    int TotalAmount,
    IReadOnlyList<EnchantmentStackSlice> GameplaySlices,
    IReadOnlyList<EnchantmentStackSlice> VisualSlices,
    IReadOnlyList<EnchantmentModel> LiveInstances,
    IReadOnlyDictionary<EnchantmentModel, Api.ScopeRuntimeStateView>? ScopeStates = null)
{
    public int ActiveInstanceCount => LiveInstances.Count(instance => instance.Status != EnchantmentStatus.Disabled);
    public int ActiveTotalAmount => GameplaySlices.Where(static slice => slice.IsActive).Sum(static slice => slice.Amount);
    public int ActiveGameplaySliceCount => GameplaySlices.Count(static slice => slice.IsActive);
    public int ActiveVisualSliceCount => VisualSlices.Count(static slice => slice.IsActive);

    public int GetExecutionCount(HookExecutionMode executionMode)
    {
        return executionMode switch
        {
            HookExecutionMode.MergedTotal => ActiveTotalAmount,
            HookExecutionMode.PerVisualSlice => ActiveVisualSliceCount,
            HookExecutionMode.PerLiveInstance => ActiveInstanceCount,
            HookExecutionMode.FirstActiveInstanceOnly => ActiveInstanceCount > 0 ? 1 : 0,
            _ => ActiveInstanceCount,
        };
    }

    /// <summary>
    /// Convenience accessor for the scope runtime state of a specific enchantment instance.
    /// Returns <c>null</c> when <paramref name="enchantment"/> is not in this snapshot's
    /// <see cref="ScopeStates"/> (e.g. the enchantment has no scope configured, or the
    /// snapshot was produced by a code path that doesn't populate scope states).
    /// </summary>
    public Api.ScopeRuntimeStateView? StateOf(EnchantmentModel enchantment)
    {
        if (ScopeStates == null || enchantment == null) return null;
        return ScopeStates.TryGetValue(enchantment, out Api.ScopeRuntimeStateView? view) ? view : null;
    }
}

public static class MultiEnchantmentStackApi
{
    internal static EnchantmentStackDefinition GetDefinition(Type enchantmentType)
    {
        ArgumentNullException.ThrowIfNull(enchantmentType);
        return MultiEnchantmentStackSupport.GetDefinition(enchantmentType);
    }

    internal static EnchantmentExecutionPolicy GetExecutionPolicy(Type enchantmentType)
    {
        ArgumentNullException.ThrowIfNull(enchantmentType);
        return MultiEnchantmentStackSupport.GetExecutionPolicy(enchantmentType);
    }

    internal static HookExecutionMode GetExecutionMode(Type enchantmentType, EnchantmentHookKind hookKind)
    {
        ArgumentNullException.ThrowIfNull(enchantmentType);
        return MultiEnchantmentStackSupport.GetExecutionMode(enchantmentType, hookKind);
    }

    internal static EnchantmentStackSnapshot GetSnapshot(EnchantmentModel enchantment)
    {
        ArgumentNullException.ThrowIfNull(enchantment);
        return MultiEnchantmentStackSupport.GetSnapshot(enchantment);
    }

    internal static IReadOnlyList<EnchantmentStackSnapshot> GetSnapshots(CardModel? card)
    {
        return MultiEnchantmentStackSupport.GetSnapshots(card);
    }

    internal static int GetHookExecutionCount(EnchantmentModel enchantment, EnchantmentHookKind hookKind)
    {
        ArgumentNullException.ThrowIfNull(enchantment);
        EnchantmentStackSnapshot snapshot = GetSnapshot(enchantment);
        if (snapshot.Definition.Behavior == EnchantmentStackBehavior.MergeAmount &&
            !ReferenceEquals(snapshot.AnchorInstance, enchantment))
        {
            return 0;
        }

        return snapshot.GetExecutionCount(GetExecutionMode(snapshot.EnchantmentType, hookKind));
    }
}
